server:
  port: 8332
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: uiot-service-connectivity
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: uiot-service-connectivity
  kafka:
    streams:
      application-id: ${spring.application.name}
      bootstrap-servers: localhost:9092
springdoc:
  api-docs:
    path: /v3/api-docs
uiot:
  vhost: /
  routing-key-template: telemetry.%s.%s
  username-context-separator: \.
  system-events-topic: uiot-system-events
