server:
  port: 8335
spring:
  application:
    name: uiot-service-things
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: uiot-service-things
  jackson:
    default-property-inclusion: non_null
uiot:
  things:
    connectivity-url: http://localhost:8333/api/rooms/{roomUid}/things/{thingUid}/connectivity
