server:
  port: 8334
spring:
  application:
    name: uiot-service-rules
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: uiot-service-rules
  jackson:
    default-property-inclusion: non_null
uiot:
  system-events-topic: uiot-system-events
