server:
  port: 8333
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: uiot-service-history
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: uiot-service-history
  kafka:
    streams:
      application-id: ${spring.application.name}
      bootstrap-servers: localhost:9092
  jackson:
    default-property-inclusion: non_null
springdoc:
  api-docs:
    path: /v3/api-docs
uiot:
  thing-events-topic: uiot-thing-events
  thing-metadata-topic: uiot-service-history_thing-metadata
  keyed-thing-events-topic: uiot-service-history_keyed-thing-events
  system-events-topic: uiot-system-events
