version: "3"
services:

  uiot-gateway:
    image: traefik:2.4.14
    ports:
      - 127.0.0.1:8330:80
    volumes:
      - ./uiot-gateway/traefik.toml:/etc/traefik/traefik.toml:ro
    networks:
      - uiot

  uiot-service-accounting:
    image: uiot-service-accounting:latest
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      SPRING_DATA_MONGODB_DATABASE: uiot-service-accounting
      SPRING_KAFKA_STREAMS_BOOTSTRAP_SERVERS: kafka:29092
      UIOT_METRICS_TOPIC: uiot-accounting
      UIOT_WINDOWS_TOPIC: uiot-accounting-windows
      UIOT_WINDOWS_SIZE: "1m"
    networks:
      - uiot

  uiot-service-connectivity:
    image: uiot-service-connectivity:latest
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      SPRING_DATA_MONGODB_DATABASE: uiot-service-connectivity
      SPRING_KAFKA_STREAMS_BOOTSTRAP_SERVERS: kafka:29092
      UIOT_VHOST: /
      UIOT_ROUTING_KEY_TEMPLATE: telemetry.%s.%s
      UIOT_USERNAME_CONTEXT_SEPARATOR: \.
      UIOT_KAFKA_SYSTEM_EVENTS_TOPIC: uiot-system-events
    networks:
      - uiot

  uiot-service-history:
    image: uiot-service-history:latest
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      SPRING_DATA_MONGODB_DATABASE: uiot-service-history
      SPRING_KAFKA_STREAMS_BOOTSTRAP_SERVERS: kafka:29092
      UIOT_THING_EVENTS_TOPIC: uiot-thing-events
      UIOT_THING_METADATA_TOPIC: uiot-service-history_thing-metadata
      UIOT_KEYED_THING_EVENTS_TOPIC: uiot-service-history_keyed-thing-events
      UIOT_SYSTEM_EVENTS_TOPIC: uiot-system-events
    networks:
      - uiot

  uiot-service-rooms:
    image: uiot-service-rooms:latest
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      SPRING_DATA_MONGODB_DATABASE: uiot-service-rooms
      SPRING_KAFKA_STREAMS_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:29092
      UIOT_SYSTEM_EVENTS_TOPIC: uiot-system-events
    networks:
      - uiot

  uiot-service-rules:
    image: uiot-service-rules:latest
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      SPRING_DATA_MONGODB_DATABASE: uiot-service-rules
      UIOT_SYSTEM_EVENTS_TOPIC: uiot-system-events
    networks:
      - uiot

  uiot-service-telemetry:
    image: uiot-service-telemetry:latest
    environment:
      SPRING_RABBITMQ_ADDRESSES: rabbitmq:5672
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:29092
      UIOT_RABBITMQ_ROUTING_KEY_REGEXP: ^telemetry\.(.*)\.(.*)$$
      UIOT_RABBITMQ_ROUTING_KEY: telemetry.*.*
      UIOT_RABBITMQ_INPUT_QUEUE: uiot-telemetry-inbound
      UIOT_KAFKA_THING_EVENTS_TOPIC: uiot-thing-events
      UIOT_KAFKA_ACCOUNTING_TOPIC: uiot-accounting
    networks:
      - uiot

  uiot-service-things:
    image: uiot-service-things:latest
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      SPRING_DATA_MONGODB_DATABASE: uiot-service-things
      SPRING_KAFKA_STREAMS_BOOTSTRAP_SERVERS: kafka:29092
      UIOT_CONNECTIVITY_INTEGRATION_URL: http://uiot-service-connectivity:8080/api/rooms/{roomUid}/things/{thingUid}/connectivity
      UIOT_SYSTEM_EVENTS_TOPIC: uiot-system-events
    networks:
      - uiot

networks:
  uiot:
    external: true
