[http]

  [http.routers]
    #########################
    ###  Service Routers  ###
    #########################

    [http.routers.uiot-service-accounting]
      rule = "Method(`GET`) && Path(`/api/accounting`)"
      service = "uiot-service-accounting"
      priority = 10

    [http.routers.uiot-service-connectivity]
      rule = "Method(`GET`) && PathRegexp(`^/api/rooms/[^/]+/things/[^/]+/connectivity$`) || Method(`POST`) && PathRegexp(`^/api/rooms/[^/]+/things/[^/]+/connectivity$`) || Method(`PUT`) && PathRegexp(`^/api/rooms/[^/]+/things/[^/]+/connectivity$`) || Method(`DELETE`) && PathRegexp(`^/api/rooms/[^/]+/things/[^/]+/connectivity$`) || Method(`PUT`) && PathRegexp(`^/api/rooms/[^/]+/things/[^/]+/connectivity/password$`) || Method(`POST`) && Path(`/auth/resource`) || Method(`POST`) && Path(`/auth/topic`) || Method(`POST`) && Path(`/auth/user`) || Method(`POST`) && Path(`/auth/vhost`)"
      service = "uiot-service-connectivity"
      priority = 40

    [http.routers.uiot-service-history]
      rule = "Method(`GET`) && PathRegexp(`^/api/rooms/[^/]+/history$`) || Method(`GET`) && PathRegexp(`^/api/rooms/[^/]+/things/[^/]+/last-state$`)"
      service = "uiot-service-history"
      priority = 30

    [http.routers.uiot-service-rooms]
      rule = "Method(`GET`) && Path(`/api/rooms`) || Method(`POST`) && Path(`/api/rooms`) || Method(`GET`) && PathRegexp(`^/api/rooms/[^/]+$`) || Method(`PUT`) && PathRegexp(`^/api/rooms/[^/]+$`) || Method(`DELETE`) && PathRegexp(`^/api/rooms/[^/]+$`)"
      service = "uiot-service-rooms"
      priority = 20

    [http.routers.uiot-service-rules]
      rule = "Method(`GET`) && PathRegexp(`^/api/rooms/[^/]+/rules$`) || Method(`POST`) && PathRegexp(`^/api/rooms/[^/]+/rules$`) || Method(`GET`) && PathRegexp(`^/api/rooms/[^/]+/rules/[^/]+$`) || Method(`DELETE`) && PathRegexp(`^/api/rooms/[^/]+/rules/[^/]+$`)"
      service = "uiot-service-rules"
      priority = 30

    [http.routers.uiot-service-things]
      rule = "Method(`GET`) && PathRegexp(`^/api/rooms/[^/]+/things$`) || Method(`POST`) && PathRegexp(`^/api/rooms/[^/]+/things$`) || Method(`GET`) && PathRegexp(`^/api/rooms/[^/]+/things/[^/]+$`) || Method(`PUT`) && PathRegexp(`^/api/rooms/[^/]+/things/[^/]+$`) || Method(`DELETE`) && PathRegexp(`^/api/rooms/[^/]+/things/[^/]+$`)"
      service = "uiot-service-things"
      priority = 30

    ############################
    ###  Swagger UI Routers  ###
    ############################

    [http.routers.uiot-swagger-ui]
      rule = "Path(`/`) || Path(`/swagger-ui.css`) || Path(`/index.css`) || Path(`/swagger-ui-bundle.js`) || Path(`/swagger-ui-standalone-preset.js`) || Path(`/swagger-initializer.js`) || Path(`/favicon-16x16.png`) || Path(`/favicon-32x32.png`)"
      service = "uiot-swagger-ui"
      priority = 60

    [http.routers.accounting-swagger]
      rule = "Path(`/accounting/v3/api-docs`)"
      service = "uiot-service-accounting"
      middlewares = ["accounting-swagger-strip"]
      priority = 50

    [http.routers.connectivity-swagger]
      rule = "Path(`/connectivity/v3/api-docs`)"
      service = "uiot-service-connectivity"
      middlewares = ["connectivity-swagger-strip"]
      priority = 50

    [http.routers.history-swagger]
      rule = "Path(`/history/v3/api-docs`)"
      service = "uiot-service-history"
      middlewares = ["history-swagger-strip"]
      priority = 50

    [http.routers.rooms-swagger]
      rule = "Path(`/rooms/v3/api-docs`)"
      service = "uiot-service-rooms"
      middlewares = ["rooms-swagger-strip"]
      priority = 50

    [http.routers.rules-swagger]
      rule = "Path(`/rules/v3/api-docs`)"
      service = "uiot-service-rules"
      middlewares = ["rules-swagger-strip"]
      priority = 50

    [http.routers.things-swagger]
      rule = "Path(`/things/v3/api-docs`)"
      service = "uiot-service-things"
      middlewares = ["things-swagger-strip"]
      priority = 50

  [http.middlewares]

    ################################
    ###  Swagger UI Middlewares  ###
    ################################

    [http.middlewares.accounting-swagger-strip.stripPrefix]
      prefixes = ["/accounting"]

    [http.middlewares.connectivity-swagger-strip.stripPrefix]
      prefixes = ["/connectivity"]

    [http.middlewares.history-swagger-strip.stripPrefix]
      prefixes = ["/history"]

    [http.middlewares.rooms-swagger-strip.stripPrefix]
      prefixes = ["/rooms"]

    [http.middlewares.rules-swagger-strip.stripPrefix]
      prefixes = ["/rules"]

    [http.middlewares.things-swagger-strip.stripPrefix]
      prefixes = ["/things"]

  [http.services]
    ##################
    ###  Services  ###
    ##################

    [[http.services.uiot-service-accounting.loadBalancer.servers]]
      url = "http://uiot-service-accounting:8080/"

    [[http.services.uiot-service-connectivity.loadBalancer.servers]]
      url = "http://uiot-service-connectivity:8080/"

    [[http.services.uiot-service-history.loadBalancer.servers]]
      url = "http://uiot-service-history:8080/"

    [[http.services.uiot-service-rooms.loadBalancer.servers]]
      url = "http://uiot-service-rooms:8080/"

    [[http.services.uiot-service-rules.loadBalancer.servers]]
      url = "http://uiot-service-rules:8080/"

    [[http.services.uiot-service-things.loadBalancer.servers]]
      url = "http://uiot-service-things:8080/"

    [[http.services.uiot-swagger-ui.loadBalancer.servers]]
      url = "http://uiot-swagger-ui:8080/"
