server:
  port: 8334
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: uiot-service-rooms
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: uiot-service-rooms
  kafka:
    streams:
      bootstrap-servers: localhost:9092
    producer:
      client-id: ${spring.application.name}
      bootstrap-servers: localhost:9092
      retries: 3
  jackson:
    default-property-inclusion: non_null
springdoc:
  api-docs:
    path: /v3/api-docs
uiot:
  system-events-topic: uiot-system-events
