server:
  port: 8336
spring:
  application:
    name: uiot-service-telemetry
  rabbitmq:
    addresses: localhost:5672
    username: user
    password: user
  kafka:
    producer:
      client-id: ${spring.application.name}
      bootstrap-servers: localhost:9092
      retries: 3
  jackson:
    default-property-inclusion: non_null
uiot:
  rabbitmq-routing-key-regexp: ^telemetry\.(.*)\.(.*)$
  rabbitmq-routing-key: telemetry.*.*
  rabbitmq-input-queue: uiot-telemetry-inbound
  kafka-thing-events-topic: uiot-thing-events
  kafka-accounting-topic: uiot-accounting
