server:
  port: 8330
spring:
  application:
    name: uiot-service-accounting
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: uiot-service-accounting
  kafka:
    producer:
      client-id: ${spring.application.name}
      bootstrap-servers: localhost:9092
      retries: 3
  jackson:
    default-property-inclusion: non_null
uiot:
  accounting:
    metrics-topic: uiot-accounting
    windows-topic: uiot-accounting-windows
    windows-size: 1m
