server:
  port: 8331
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: uiot-service-accounting
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: uiot-service-accounting
  kafka:
    streams:
      application-id: ${spring.application.name}
      bootstrap-servers: localhost:9092
  jackson:
    default-property-inclusion: non_null
springdoc:
  api-docs:
    path: /v3/api-docs
uiot:
  metrics-topic: uiot-accounting
  windows-topic: uiot-accounting-windows
  windows-size: 1m
